#!/bin/bash
# usage: targetMatchingAssessment.sh </path/to/allseqs.fa> </path/to/blastHitTable> ["pattern target names"]
module load R

# Set variables
ALLSEQS=$1 # Path to the fasta file containing all of the query (=subject) sequences.
MATCHES=$2 # Path to the hit table generated by blast. Table format = 6.
TARGETNAMES=${3:-"WeinellEntry"} # text string present in the names of all of the target sequences

Rscript '/panfs/pfs.local/home/j926w878/work/conda/snakecap/targetMatchingAssessment.R' $ALLSEQS $MATCHES $TARGETNAMES
