#!/bin/bash
# usage: sbatch --nodes=1 --partition=sixhour "/panfs/pfs.local/home/j926w878/work/conda/snakecap/test11.sh" "A" <BLASTDBDIR> <QUERYPATH> <ALLSAMPLESKEYPATH> <MATCHESDIR>
# module load anaconda
# conda activate py36
module load 'blast+/2.9.0'

### Description:
# BLASTs the consensus sequence of each group of SeqCap + targetRef sequences against each sample genome blast database

MODE=$1    ### "A" (main job) or "B" (each subjob called from main job)

if [ "$MODE"="A" ] ; then
  BLASTDBDIR=$2         # Path to the directory containing the blast databases of subject samples; subjects will be those of type "genome" defined in SEQFILE.
  QUERYPATH=$3          # Path to the fasta file containing consensus sequence of the SeqCap and targetRef sequences in each group.
  ALLSAMPLESKEYPATH=$4  # Path to the "~/allsamples_key.txt" file generated by '03-temp.sh'? and containing the original sample names in column 1, blast database sample names in column 2, and sequence type (SeqCap, targetRef, or genome) in column 3.
  MATCHESDIR=$5         # Where to save the hit tables
  
  # Path to this bash script. 
  SHij="/panfs/pfs.local/home/j926w878/work/conda/snakecap/test11.sh"
  
  # BLASTDBDIR="/panfs/pfs.local/home/j926w878/scratch/scratch_v3/SequenceCapture/SnakeCap_AllSamples/blast_database10/databases/blast_db"
  # QUERYPATH="/panfs/pfs.local/home/j926w878/scratch/scratch_v3/SequenceCapture/SnakeCap_AllSamples/blast_database10/groupAlignments_SeqCapAndTargetRef_consensus_InputSeqsMax100.fasta"
  # ALLSAMPLESKEYPATH="/panfs/pfs.local/home/j926w878/scratch/scratch_v3/SequenceCapture/SnakeCap_AllSamples/blast_database10/allsamples_key.txt"
  # MATCHESDIR="/panfs/pfs.local/home/j926w878/scratch/scratch_v3/SequenceCapture/SnakeCap_AllSamples/blast_database10/matches_consensusSeqCapAndTargetRef_vs_genomes"
  
  [ -d "$MATCHESDIR" ] && mkdir $MATCHESDIR
  
  SUBJECTNAMES=$(awk '{if ($3=="genome") {print $1}}' "$ALLSAMPLESKEYPATH")
  DATABASESDIR=$BLASTDBDIR"/databases/"
  DBPREFIX=$DATABASESDIR"/blast_db"

  for SUBJECTj in "$SUBJECTNAMES"; do
    DBPATHj=$DBPREFIX"_"$SUBJECTj
    MATCHESij=$MATCHESDIR'/Qconsensus_S'$SUBJECTj'_matches.txt'
    sbatch --nodes=1 --ntasks-per-node=4 --time=6:00:00 --partition=sixhour $SHij "B" $BLASTDBDIR $DBPATHj $QUERYPATH $MATCHESij
  done
fi

if [ "$MODE"="B" ] ; then
  DBPATHj=$3
  QUERYPATH=$4
  MATCHESij=$5
  echo $DBPATHj"_"$QUERYPATH
  blastn -task 'blastn' -db "$DBPATHj" -query "$QUERYPATH" -out "$MATCHESij" -max_hsps 1 -evalue 0.0000000001 -outfmt 6 -num_threads 10 -word_size 100 -gapopen 5 -gapextend 2 -reward 2 -penalty '-3' -perc_identity 0
fi




