#' Phylogenetic Congruency Network from Congruency Matrix
#' 
#' Plot the result of the function multiple.congruency.test as a network to summarize topological discordance among phylogenies.
#' 
#' @param congruency.matrix The data.frame generated by running multiple.congruency.test, which is used as input in this function.
#' @param plot.network Whether or not to plot the network (default is true).
#' @return An igraph network object. Each node is a tree and edges connect trees that have congruent topologies. Returns NA if all trees incongruent.
#' @export 
congruency.network <- function(congruency.matrix,plot.network=T){
	congruency.matrix <- as(congruency.matrix,"matrix")
	# logical vector indicating rows of congruency.matrix with pairs of congruent trees
	edges.logic <- grepl(TRUE, (congruency.matrix[,"tree1"] != congruency.matrix[,"tree2"] & congruency.matrix[,"congruent"]=="TRUE"))
	if(!any(edges.logic)){
		result <- NA
	} else {
		mat.congruent    <- congruency.matrix[which(congruency.matrix[,"tree1"] != congruency.matrix[,"tree2"] & congruency.matrix[,"congruent"]=="TRUE"),]
		edge_list        <- tibble::tibble(from = mat.congruent[,1], to = mat.congruent[,2])
		node_list        <- tibble::tibble(id = unique(congruency.matrix[,1]))
		result.igraph    <- igraph::graph_from_data_frame(d = edge_list, vertices = node_list, directed = FALSE)
		
		if(plot.network==T){
			plot(result.igraph)
		}
		result <- result.igraph
	}
	result
}
