#' Phylogenetic Congruency Network from Congruency Matrix
#' 
#' Plot the result of the function multiple.congruency.test as a network to summarize topological discordance among phylogenies.
#' 
#' @param congruency.matrix The matrix object generated by running multiple.congruency.test, which is used as input in this function.
#' @param plot.network Whether or not to plot the network (default is true).
#' @return An igraph network object. Each node is a tree and edges connect trees that have congruent topologies.
#' @export 
congruency.network <- function(congruency.matrix,plot.network=T){
	mat.congruent    <- congruency.matrix[which(congruency.matrix[,"tree1"] != congruency.matrix[,"tree2"] & congruency.matrix[,"congruent"]=="TRUE"),]
	edge_list        <- tibble::tibble(from = mat.congruent[,1], to = mat.congruent[,2])
	node_list        <- tibble::tibble(id = unique(congruency.matrix[,1]))
	result.igraph    <- igraph::graph_from_data_frame(d = edge_list, vertices = node_list, directed = FALSE)
	if(plot.network==T){
		plot(result.igraph)
	}
	result.igraph
}
